### PR TITLE
Dialyzer

### PR DESCRIPTION
**Pull request by NobbZ**
Things to do:
- [x] Add [`dialyxir`](https://hex.pm/packages/dialyxir)
- [x] Add it to travis script
- [x] Activate travis caching of the generated `global.plt`
- [x] Test if it really caches

---
- [x] Make it really fail when there are type inconsistencies…

Shall I really do that last one? Or shall we keep dialyzer only for informativ output? **Discuss!**

### CODE REVIEW

**Comment by NobbZ** [comment]
Please do not merge before I figured out how to cache the `plt`-file of Elixir!

**Comment by NobbZ** [comment]
OK, I think I have done the caching. But allow me to do some tests on this during the next 3 days. I'll remove the `WIP`-label as soon as I think this is ready.

**Comment by NobbZ** [comment]
Caching seems to work as best I can do it for now.

I wish I were able to specify a cache for all the compiled dependencies, but thats going to get a hard one. Either we need to specify each dependencies binary-dir as its own cache, or we need to specify the `_buid`-folder as a whole for beeing cached and delete the compiled `exads`-artifacts in that folder. I don't like both of this solutions.

But since this PR is mostly about dialyzer I do leave that one open for now.

Last thing that needs to be discussed:
Shall we have a failing testbuild if `dialyzer` finds anything or shall we keep it as an informative information in the logs?

**Comment by sashaafm** [comment]
Hello @NobbZ, thank you for another contribution :+1: I'm not familiar with dialyzer, but I've used similar tools in the past (for Java mainly), so let me please dig a bit into dialyzer first so we can discuss this in a more meaningful manner. But for a first answer, I think that yes the build should fail if dialyzer finds anything wrong.

**Comment by sashaafm** [comment]
Hello again @NobbZ, I read a bit about Dyalizer. In my opinion I think the the testbuild sould fail if dyalizer finds anything, I think this is an important aspect for a project of this sort. I've never used Dyalizer though, can it be set up with Travis easily?

**Comment by NobbZ** [comment]
This PR does already all the setup on travis.

Only thing thats left for now is activating the halt-on-fail. I will do it tonight/tomorrow mornning.

The bigger Problem for most people will obviously be reading the dialyzer output. The output is in erlang syntax. So dialyzer means switching back and forth between erlang-syntax of elixir-names/types and vice versa.

**Comment by NobbZ** [comment]
OK, I updated the travis settings such that we should get failing tests for invalid typestuff.

This does actually mean, that we won't get passing travis from the moment this gets merged until we repaired everything.

I do leave repairing the typeerrors open for another PR. These PRs should be done by the people feeling responsible for the corresponding modules.

**Comment by sashaafm** [comment]
Hello @NobbZ, can I merge?

**Comment by NobbZ** [comment]
It's ready to merge yes.

**Pull request merged**
