### PR TITLE
Add Travis CI build and Inch CI docs statuses

### PR DESCRIPTION
**Pull request by ghost**
Especially for a data structures and algorithms project, I thought it necessary to have the build and docs status badges displayed proudly in the README.

@sashaafm: You will need to sign up with each of these services, and tell Travis CI to watch this repo. I have already changed the username in the images and links, so all you need to do is merge to master.

Great project! I hope to contribute more in the future.

### CODE REVIEW

**Comment by NobbZ** [comment]
Put `inch` to `:dev`, hen you can save up a lot of recompiling. Doesn't really matter on current size, but will make a difference later as the project grows. 

Also it is a lot easier then to do an `mix inch` locally before committing changes or newly added stuff.

**Comment by ghost** [comment]
I followed the guide on Inch CI, and it said to use the `:docs` environment atom. If you want to run the Inch report manually you can use this command: `MIX_ENV=docs mix inch.report`, as added to the `.travis.yml`.

**Comment by NobbZ** [comment]
Yeah, that's the guide on the page, but the README of the hex-package on
Github does explain it my way. He seems not to really keep all his pages up
to sync...

James Wheaton notifications@github.com schrieb am Do., 25. Feb. 2016
19:54:

**Comment by ghost** [comment]
@NobbZ Done. I used the instructions from the `inch_ex` project's README.

**Comment by NobbZ** [comment]
Now we have to wait for @sashaafm. I can't activate the tools.

James Wheaton notifications@github.com schrieb am Do., 25. Feb. 2016
20:10:

**Pull request merged**
